<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
	<Description>OpenIoT library for .net</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>OpenIoT.Lib</PackageId>
    <Version>0.0.9.0</Version>
    <Authors>Ivan Donev</Authors>
  <Company>Palitri</Company>  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="System.IO.Ports" Version="6.0.0" />
  </ItemGroup>

</Project>
